### ISSUE TITLE
监听事件能够获取到Position吗？

### ISSUE THREAD

**Issue by FynnJason** [hgDendi/ExpandableRecyclerView#2]
点击childItem，可以为接口的方法增加2个参数，分别是groupPosition和childPosition

**Comment by chdendi** [comment]
可以的，但是因为Callback里传入了GroupBean和ChildBean，感觉冗余，就没有加进去。
你可以把库拉下来修改回调，应该很容易拿到。
之所以没有加参数是觉得在列表里这些是属于易失的属性，所以还是以Bean为准。
