### ISSUE TITLE
Enhancement: 存在不没有group的item， 也想将其展示

### ISSUE THREAD

**Issue by caprice** [hgDendi/ExpandableRecyclerView#5]
现有需求：存在只有childitem而没有group的话，需要与group平行并展示；有group的话就同目前一样

**Comment by chdendi** [comment]
自己在外部做一层转换吧，我没有加这种自动处理的逻辑，加上的话感觉会变乱。而且我的每一个childItem都是要跟group绑定才能存在的，设计时候就不支持这种情况。

**Comment by cWX411904** [comment]
请问大神，怎样控制childItem默认是展开的状态？

**Comment by chdendi** [comment]
BaseExpandableRecyclerViewAdapter#mExpandGroupSet设置到这个里面，如果全展开可以在构造的时候把GroupItem都传进去。

**Comment by cWX411904** [comment]
能贴下主要代码吗？本人水平有限，多谢了 @hgDendi

**Comment by cWX411904** [comment]
哦，已经改好了，BaseExpandableRecyclerViewAdapter本身就提供了展开的方法，我在设置Adapter时候，提前让它展开就可以了：
for (BillDetailGroupViewBean groupViewBean : mDatas) {
            mAdapter.expandGroup(groupViewBean);
        }
        mRecyclerView.setAdapter(mAdapter);

**Comment by cWX411904** [comment]
另外调试的时候还有个问题，如果顺序是：
mRecyclerView.setAdapter(mAdapter);
        for (BillDetailGroupViewBean groupViewBean : mDatas) {
            mAdapter.expandGroup(groupViewBean);
        }
我修改子item或者添加一个子item，就会出现崩溃：日志是：
    java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 1(offset:4).state:4
        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5504)
这里面的原因不是很理解，请问楼主知道吗？

**Comment by chdendi** [comment]
子item是指的GroupBean吗？

**Comment by chdendi** [comment]
贴一下简单代码呢

**Comment by cWX411904** [comment]
loadMonthBill这个方法是从数据库查询数据成功后的回调：
@Override
    public void loadMonthBill(List<BillDetailGroupViewBean> detaiList, int type) {
        if(DEBUG) Log.e(TAG, "."+"detaList.size = " + detaiList.size());
        if (detaiList.size() != 0) {
            for (BillDetailGroupViewBean groupViewBean : detaiList) {
                if(DEBUG) Log.e(TAG, "."+"groupViewBean.getChildViewList().size() = " + groupViewBean.getChildViewList().size());
            }
        }
        mDatas = detaiList;
        if(mDatas.size() == 0) {
            if(DEBUG) Log.e(TAG, "."+"查询的数据为空");
            total_in_money.setText("+0");
            total_out_money.setText("-0");
            out_out_tx.setVisibility(View.INVISIBLE);
        } else {
            double income = 0.0;
            double expand = 0.0;
            for (BillDetailGroupViewBean groupViewBean : mDatas) {
                income += groupViewBean.getIncome();
                expand += groupViewBean.getSpend();
            }
            if(DEBUG) Log.e(TAG, "."+"当月总收入：" + income + ",当月总支出：" + expand);
            total_in_money.setText("+" + CommonUtils.format(income));
            total_out_money.setText("-" + CommonUtils.format(expand));
            double aFloat = SPNewUtils.getInstance(getContext()).getFloat(Constants.MOUTH_KEY, (float) 6000.00);
            if(DEBUG) Log.e(TAG, "."+"SP中存储的月预警值为：" + aFloat);
            if (expand > aFloat) {
                out_out_tx.setVisibility(View.VISIBLE);
            } else {
                out_out_tx.setVisibility(View.INVISIBLE);
            }
        }
        mAdapter = new BillDetailAdapter(mDatas,this, iconMap);
        mAdapter.setEmptyViewProducer(new ViewProducer() {
            @Override
            public RecyclerView.ViewHolder onCreateViewHolder(ViewGroup parent) {
                return new DefaultEmptyViewHolder(
                        LayoutInflater.from(parent.getContext()).inflate(R.layout.item_bill_detail_empth, parent, false));
            }

            @Override
            public void onBindViewHolder(RecyclerView.ViewHolder holder) {

            }
        });
        if (mDatas != null && mDatas.size() > 0) {
            for (BillDetailGroupViewBean groupViewBean : mDatas) {
                mAdapter.expandGroup(groupViewBean);
            }
        }
        mRecyclerView.setAdapter(mAdapter);
    }



BillDetailGroupViewBean这个类是GroupBean
public class BillDetailGroupViewBean implements BaseExpandableRecyclerViewAdapter.BaseGroupBean<BillDetailChildViewBean>{

    private String date;//"18日"
    private String week;//"周三"
    private double spend;//当天支出
    private double income;//当天收入
    private List<BillDetailChildViewBean> childViewList;

    public BillDetailGroupViewBean(@NonNull String date, @NonNull String week, @NonNull double spend, @NonNull double income, @NonNull List<BillDetailChildViewBean> childViewList) {
        this.date = date;
        this.week = week;
        this.spend = spend;
        this.income = income;
        this.childViewList = childViewList;
    }

    public String getDate() {
        return date;
    }

    public String getWeek() {
        return week;
    }

    public double getSpend() {
        return spend;
    }

    public double getIncome() {
        return income;
    }

    public List<BillDetailChildViewBean> getChildViewList() {
        return childViewList;
    }

    @Override
    public int getChildCount() {
        return childViewList.size();
    }

    @Override
    public BillDetailChildViewBean getChildAt(int childIndex) {
        return childViewList.size() <= childIndex ? null : childViewList.get(childIndex);
    }

    @Override
    public boolean isExpandable() {
        return getChildCount() > 0;
    }
}

BillDetailChildViewBean这个类是childBean
public class BillDetailChildViewBean implements Serializable{

    private Long id;
    private String icon;//图标的icon
    private String iconName;//图标的详情
    private double price;//该类型花费或支出的钱数
    private int type;//1代表收入；2代表支出

    public BillDetailChildViewBean(Long id, String icon, String iconName, double price, int type) {
        this.id = id;
        this.icon = icon;
        this.iconName = iconName;
        this.price = price;
        this.type = type;
    }

    public Long getId() {
        return id;
    }

    public String getIcon() {
        return icon;
    }

    public String getIconName() {
        return iconName;
    }

    public double getPrice() {
        return price;
    }

    public int getType() {
        return type;
    }
}
